disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - todo
  - type_body_length
  - type_name

opt_in_rules: []
