import Foundation

enum LocalizationStore {
    static let strings: [AppLanguage: [String: String]] = [
        .german: [
            "app_name": "CRISIS 2050",
            "tab_overview": "Übersicht",
            "tab_comparison": "Vergleich",
            "tab_metals": "Edelmetalle",
            "tab_crisis": "Krisen",
            "tab_consultation": "Beratung",
            "cta_title": "Beratung anfragen",
            "cta_subtitle": "Sichern Sie Ihr Vermögen mit Edelmetallen",
            "overview_title": "Übersicht",
            "overview_hero_title": "Vermögenssicherung",
            "overview_hero_subtitle": "Aktuelle Prognose",
            "overview_forecast_label": "Prognose",
            "overview_forecast_hint": "Vorsicht empfohlen - Absicherung priorisieren.",
            "overview_metals_focus": "Edelmetalle im Fokus",
            "overview_metals_focus_subtitle": "Gold & Silber im aktuellen Marktumfeld",
            "overview_macro_title": "Makro-Lage",
            "overview_macro_subtitle": "Inflation, Wechsel & Wachstum je Region",
            "why_metals_title": "Warum Edelmetalle und Struktur",
            "why_metals_bullet_1": "Physischer Wert, unabhängig von Währungen",
            "why_metals_bullet_2": "Schutz vor Inflation und Kaufkraftverlust",
            "why_metals_bullet_3": "Stabilität in Kriegen und Wirtschaftskrisen",
            "why_metals_bullet_4": "Strukturierter Vermögensschutz durch planbare Allokation",
            "why_metals_bullet_5": "Sichere Lagerung im Zollfreilager außerhalb des Bankensystems",
            "comparison_title": "Vergleich",
            "comparison_section_title": "Asset-Klassen-Vergleich",
            "comparison_section_subtitle": "Historisch & Prognose 2025–2050",
            "comparison_period": "Zeitraum",
            "comparison_mode_history": "Historisch",
            "comparison_mode_forecast": "Prognose",
            "comparison_chart_title": "Wertentwicklung",
            "comparison_chart_subtitle": "Tippen Sie auf den Chart, um Details zu sehen.",
            "comparison_performance_title": "Performance-Übersicht",
            "comparison_performance_subtitle": "Historisch und Prognose",
            "comparison_no_data": "Keine Marktdaten verfügbar.",
            "comparison_loading": "Lade Marktdaten…",
            "comparison_macro_title": "Makro-Vergleich",
            "comparison_macro_subtitle": "Regionale Trends nebeneinander",
            "comparison_macro_loading": "Lade Makro-Daten.",
            "comparison_macro_no_data": "Keine Makro-Daten verfügbar.",
            "comparison_scenario_title": "Szenario-Labor",
            "comparison_scenario_subtitle": "Inflation, Wachstum und Verteidigung justieren",
            "comparison_scenario_inflation": "Inflation (%)",
            "comparison_scenario_growth": "Wachstum (%)",
            "comparison_scenario_defense": "Verteidigung (%% BIP)",
            "comparison_scenario_equities": "Aktien",
            "comparison_scenario_real_estate": "Immobilien",
            "comparison_scenario_metals": "Edelmetalle",
            "comparison_portfolio_title": "Portfolio-Resilienz",
            "comparison_portfolio_subtitle": "Mix aus Aktien, Immobilien und Edelmetallen",
            "metals_title": "Edelmetalle",
            "metals_selector_title": "Edelmetall auswählen",
            "metals_projection_title": "Prognose für 3 Jahre",
            "metals_projection_subtitle": "%1$@ Ausblick",
            "metals_trend_title": "Historisch & Prognose bis 2050",
            "metals_trend_subtitle": "Indexentwicklung %1$@",
            "metals_trend_loading": "Lade Marktdaten…",
            "metals_resilience_title": "Resilienz in Krisen",
            "metals_resilience_subtitle": "%1$@ in unterschiedlichen Szenarien",
            "metals_scenario_inflation": "Inflation",
            "metals_scenario_wars": "Kriege",
            "metals_scenario_wars_detail": "Geopolitische Spannungen erhöhen die Nachfrage nach sicheren Häfen.",
            "metals_scenario_recession": "Wirtschaftskrisen",
            "metals_scenario_recession_detail": "In Rezessionen dient %1$@ als Liquiditätsreserve.",
            "metals_badge_protection": "Schutz",
            "metals_badge_shield": "Absicherung",
            "metals_badge_diversification": "Diversifikation",
            "crisis_title": "Krisen",
            "crisis_overview_title": "Krisenlage",
            "crisis_overview_subtitle": "Aktuelle Hinweise aus externen Quellen",
            "crisis_overview_empty": "Keine aktuellen Hinweise.",
            "crisis_feed_title": "Krisen-Feed",
            "crisis_feed_subtitle": "Meldungen aus NewsAPI und der World Bank",
            "crisis_feed_empty": "Keine aktuellen Krisenmeldungen.",
            "crisis_category_financial": "Finanzen",
            "crisis_category_geopolitical": "Geopolitik",
            "crisis_badge_info": "Info",
            "crisis_badge_moderate": "Moderat",
            "crisis_badge_high": "Hoch",
            "crisis_detail_title": "Krisen-Details",
            "crisis_detail_missing": "Ereignis nicht gefunden.",
            "crisis_detail_time": "Zeitpunkt: %1$@",
            "crisis_detail_source": "Quelle: %1$@",
            "crisis_detail_open_source": "Quelle öffnen",
            "crisis_detail_timeline_title": "Zeitachse",
            "consultation_title": "Beratung anfragen",
            "consultation_panel_subtitle": "Für eine individuelle Beratung nutzen Sie bitte das Kontaktformular auf der Website.",
            "consultation_section_expectations": "Was Sie erwartet",
            "consultation_expectation_1": "Kostenlose Erstberatung durch Edelmetall-Experten",
            "consultation_expectation_2": "Individuelle Vermögensstrukturierung",
            "consultation_expectation_3": "Informationen zur Zollfreilager-Lagerung",
            "consultation_expectation_4": "Steuerliche Aspekte und rechtliche Absicherung",
            "consultation_section_contact": "Ihre Kontaktdaten",
            "consultation_section_message": "Nachricht",
            "consultation_name": "Name*",
            "consultation_email": "E-Mail*",
            "consultation_phone": "Telefon*",
            "consultation_message_hint": "Wie können wir Ihnen helfen?*",
            "consultation_submit": "Anfrage senden",
            "consultation_submit_success_title": "Vielen Dank",
            "consultation_submit_success_message": "Ihre Anfrage wurde gesendet. Wir melden uns zeitnah.",
            "consultation_submit_failure_title": "Senden fehlgeschlagen",
            "consultation_submit_failure_message": "Fehler beim Senden der Anfrage.",
            "consultation_privacy_note": "Mit dem Absenden stimmen Sie zu, dass wir Ihre Anfrage gemäß der Datenschutzerklärung beantworten. Wir speichern keine Daten dauerhaft auf diesem Gerät.",
            "consultation_error_name": "Bitte geben Sie Ihren Namen an.",
            "consultation_error_email": "Bitte geben Sie eine gültige E-Mail-Adresse an.",
            "consultation_error_phone": "Bitte geben Sie Ihre Telefonnummer an.",
            "consultation_error_message": "Ihre Nachricht sollte mindestens 10 Zeichen enthalten.",
            "consultation_error_invalid": "Ungültige Eingabe",
            "consultation_section_more_info": "Weitere Informationen",
            "consultation_info_1_title": "Zollfreilager-Lagerung",
            "consultation_info_1_text": "Physische Trennung vom Bankensystem, Versicherung und 24/7 Überwachung für maximale Sicherheit und Flexibilität.",
            "consultation_info_2_title": "Wert - Struktur gewinnt",
            "consultation_info_2_text": "Klare Allokation in Edelmetalle schafft Stabilität in Inflation, Währungsreformen und Krisen.",
            "settings_title": "Einstellungen",
            "settings_section_general": "Allgemein",
            "settings_currency_label": "Anzeigewährung",
            "settings_currency_hint": "Steuert, in welcher Währung Edelmetallpreise im gesamten Interface angezeigt werden.",
            "settings_watchlist_section": "Krisen-Watchlist",
            "settings_watchlist_geopolitical": "Geopolitik",
            "settings_watchlist_financial": "Konjunktur",
            "settings_thresholds_section": "Krisenschwellen",
            "settings_thresholds_label": "Sensitivität",
            "settings_thresholds_standard": "Standard",
            "settings_thresholds_sensitive": "Sensitiv",
            "settings_thresholds_conservative": "Konservativ",
            "settings_thresholds_hint": "Beeinflusst, wann Ereignisse als Hochrisiko gelten.",
            "settings_notifications_section": "Benachrichtigungen",
            "settings_notifications_label": "Benachrichtigungen",
            "settings_privacy_section": "Beratung & Datenschutz",
            "settings_privacy_policy": "Datenschutzerklärung",
            "settings_privacy_note": "Persönliche Daten verlassen Ihr Gerät nur, wenn Sie eine Anfrage senden. Es erfolgt keine lokale Speicherung.",
            "settings_transparency_note": "Alle Wirtschaftsdaten stammen aus offenen APIs von GoldPrice.org und der Weltbank.",
            "settings_contact_note": "Nutzen Sie den Tab Beratung für individuelle Fragen. Antworten erfolgen DSGVO-konform per E-Mail.",
            "settings_done": "Fertig",
            "notifications_status_active": "Aktiv",
            "notifications_status_denied": "Deaktiviert",
            "notifications_status_limited": "Begrenzt",
            "notifications_status_unknown": "Unbekannt",
            "notifications_description_active": "Sie erhalten Warnhinweise bei Prognose-Wechseln oder größeren Krisen.",
            "notifications_description_denied": "Benachrichtigungen sind ausgeschaltet. Aktivieren Sie sie in den Systemeinstellungen.",
            "notifications_description_limited": "Temporäre Berechtigung – bestätigen Sie sie, um kritische Hinweise zu behalten.",
            "notifications_description_undetermined": "Noch keine Berechtigung angefragt.",
            "notifications_action_open_settings": "Systemeinstellungen öffnen",
            "notifications_action_enable": "Benachrichtigungen aktivieren",
            "notifications_action_adjust": "Berechtigung bestätigen",
            "notification_onboarding_title": "Mitteilungen",
            "notification_onboarding_headline": "Krisen-Alerts",
            "notification_onboarding_body": "Erhalten Sie einmalige Push-Mitteilungen bei Hochrisiko-Ereignissen. Wir senden nur Meldungen, wenn die Lage ernst ist.",
            "notification_onboarding_toggle_title": "Echtzeit-Benachrichtigungen",
            "notification_onboarding_toggle_hint": "Nur Krisen ab Schweregrad 5 und keine Werbung.",
            "notification_onboarding_device_hint": "Sie können Ihre Entscheidung jederzeit in den Systemeinstellungen ändern.",
            "notification_onboarding_privacy_hint": "Keine Daten verlassen Ihr Gerät. Grundlage: App-Store-Richtlinie 5.1.1.",
            "notification_onboarding_enable": "Krisen-Alerts aktivieren",
            "notification_onboarding_later": "Vielleicht später",
            "notification_onboarding_error_toggle": "Aktivieren Sie die Umschaltung, um Benachrichtigungen zu erlauben.",
            "notification_onboarding_error_settings": "Bitte erlauben Sie Mitteilungen in den Systemeinstellungen.",
            "notification_banner_denied": "Krisen-Alerts deaktiviert",
            "notification_banner_limited": "Krisen-Alerts im Ruhemodus",
            "notification_banner_missing": "Krisen-Alerts noch nicht aktiviert",
            "notification_banner_message_denied": "Aktivieren Sie Benachrichtigungen, um akute Krisen sofort zu sehen.",
            "notification_banner_message_limited": "App-Mitteilungen werden momentan nur still zugestellt. Aktivieren Sie Banner/Töne.",
            "notification_banner_message_missing": "Tippen Sie hier, um Push-Mitteilungen für Hochrisiko-Lagen einzuschalten.",
            "notification_banner_action_settings": "Einstellungen öffnen",
            "notification_banner_action_adjust": "Einstellungen anpassen",
            "privacy_policy_title": "Datenschutzerklärung",
            "privacy_policy_website": "Website",
            "privacy_policy_intro": "Wir verarbeiten Ihre Daten ausschließlich auf dem Gerät oder über den Versand Ihrer Anfrage. Es gibt keine versteckten Tracker oder Cloud-Profile.",
            "privacy_section_controller_title": "Verantwortliche Stelle",
            "privacy_section_controller_body": "VermögensKompass (Vibecode GmbH) verarbeitet ausschließlich die Daten, die Sie aktiv teilen.",
            "privacy_section_collection_title": "Datenerhebung im Überblick",
            "privacy_section_collection_body": "• Markt- und Krisendaten stammen aus offen zugänglichen APIs (World Bank, USGS, NOAA, GoldPrice.org) und werden nur lokal ausgewertet.\n• Wir speichern keine personenbezogenen Daten auf unseren Servern.",
            "privacy_section_contact_title": "Kontaktaufnahme",
            "privacy_section_contact_body": "Wenn Sie auf „Beratung anfragen“ tippen, senden wir Ihre Nachricht an unser Beratungsteam. Der Versand erfolgt über eine gesicherte Verbindung; wir speichern dabei keine Kopie.",
            "privacy_section_notifications_title": "Benachrichtigungen",
            "privacy_section_notifications_body": "Krisen-Benachrichtigungen werden ausschließlich auf Ihrem Gerät verarbeitet. Sie können die Berechtigung jederzeit in den Systemeinstellungen widerrufen.",
            "privacy_section_tracking_title": "Analytics & Tracking",
            "privacy_section_tracking_body": "Kein Tracking, keine Drittanbieter-SDKs. Die App funktioniert vollständig offline mit den zuletzt synchronisierten Daten.",
            "privacy_section_rights_title": "Ihre Rechte",
            "privacy_section_rights_body": "Sie können Auskunft, Berichtigung oder Löschung Ihrer Kontaktaufnahme verlangen, indem Sie uns unter datenschutz@vermoegenskompass.de kontaktieren.",
            "offline_banner_title": "Offline-Daten",
            "offline_banner_no_sync": "Noch keine erfolgreiche Synchronisierung",
            "crisis_notification_channel": "Krisen-Alerts",
            "crisis_notification_title": "Krisenlage: %1$@",
            "crisis_notification_body": "Region: %1$@. Kategorie: %2$@.",
            "generic_ok": "Okay",
            "error_loading": "Fehler beim Laden",
            "sync_error_background_update": "Fehler beim Hintergrund-Update",
            "async_loading": "Daten werden aktualisiert.",
            "async_retry": "Erneut versuchen",
            "sync_last_successful": "Letzte Synchronisierung: %1$@",
            "sync_never_successful": "Noch keine erfolgreiche Synchronisierung",
            "consultation_submit_loading": "Wird gesendet…",
            "not_available_short": "k. A.",
            "comparison_performance_format": "Historisch %1$@ / Prognose %2$@",
            "comparison_chart_today": "Heute",
            "comparison_chart_x_label": "Jahr",
            "comparison_chart_y_label": "Wert in %1$@",
            "macro_delta_no_trend": "Kein Verlauf",
            "macro_delta_vs_previous": "%1$@%2$@%3$@ vs. Vorjahr",
            "macro_region_de": "DE",
            "macro_region_us": "US",
            "macro_region_uk": "UK",
            "macro_region_es": "ES",
            "currency_eur": "Euro (€)",
            "currency_usd": "US-Dollar ($)",
            "settings_language_section": "Sprache",
            "settings_language_label": "App-Sprache",
            "settings_language_hint": "Ändert die Sprache der Benutzeroberfläche.",
            "language_de": "Deutsch",
            "language_en": "Englisch",
            "language_fr": "Französisch",
            "language_es": "Spanisch",
            "metal_insight_24h": "24h",
            "metal_insight_change": "Veränderung",
            "metal_source_label": "Quelle: %1$@",
            "metals_scenario_inflation_detail": "%1$@ reagiert historisch positiv auf steigende Verbraucherpreise.",
            "asset_group_equities": "Aktienmärkte",
            "asset_group_real_estate": "Immobilienpreise",
            "asset_group_metals": "Edelmetalle",
            "asset_equity_de": "Deutschland Aktien",
            "asset_equity_usa": "USA Aktien",
            "asset_equity_lon": "London Aktien",
            "asset_real_estate_de": "Deutschland Immobilien",
            "asset_real_estate_es": "Spanien Immobilien",
            "asset_real_estate_fr": "Frankreich Immobilien",
            "asset_real_estate_lon": "London Immobilien",
            "asset_gold": "Gold",
            "asset_silver": "Silber",
            "macro_indicator_inflation_title": "Inflation",
            "macro_indicator_inflation_description": "Jährliche Verbraucherpreisinflation laut Weltbank",
            "macro_indicator_inflation_unit": "%",
            "macro_indicator_growth_title": "Wachstum",
            "macro_indicator_growth_description": "Reales BIP-Wachstum",
            "macro_indicator_growth_unit": "%",
            "macro_indicator_defense_title": "Verteidigung",
            "macro_indicator_defense_description": "Militärausgaben im Verhältnis zum BIP",
            "macro_indicator_defense_unit": "% BIP",
            "benner_phase_panic_title": "Panikjahr",
            "benner_phase_panic_subtitle": "Extremer Verkaufsdruck - Phase A",
            "benner_phase_panic_guidance": "Historisch folgten auf diese Jahre heftige Markteinbrüche. Liquidität sichern und Risiko begrenzen.",
            "benner_phase_good_title": "Gute Zeiten",
            "benner_phase_good_subtitle": "Hohe Preise - Phase B (Verkäufe bevorzugt)",
            "benner_phase_good_guidance": "Überdurchschnittliche Bewertungen. Gewinne sichern und Exposure reduzieren.",
            "benner_phase_hard_title": "Schwere Zeiten",
            "benner_phase_hard_subtitle": "Niedrige Preise - Phase C (Akkumulation)",
            "benner_phase_hard_guidance": "Marktpreise gelten als günstig. Positionsaufbau und Sparpläne bieten sich an.",
            "benner_entry_summary": "%1$d - %2$@",
            "watchlist_country_ukraine": "Ukraine",
            "watchlist_country_israel": "Israel",
            "watchlist_country_taiwan": "Taiwan",
            "watchlist_country_south_africa": "Südafrika",
            "watchlist_country_germany": "Deutschland",
            "watchlist_country_usa": "USA",
            "watchlist_country_uk": "Vereinigtes Königreich",
            "watchlist_country_japan": "Japan",
            "watchlist_country_china": "China",
            "crisis_summary_headline_none": "Keine Hochrisiko-Ereignisse erkennbar",
            "crisis_summary_highlight_category": "%1$dx Kategorie %2$@",
            "crisis_summary_highlight_latest": "Zuletzt %1$@ um %2$@",
            "crisis_event_title_governance": "Politische Instabilität in %1$@",
            "crisis_event_title_recession": "Rezession in %1$@",
            "crisis_summary_headline_count_one": "%d Hochrisiko-Ereignis aktiv",
            "crisis_summary_headline_count_other": "%d Hochrisiko-Ereignisse aktiv",
            "crisis_summary_highlight_region_one": "%1$dx Ereignis in %2$@",
            "crisis_summary_highlight_region_other": "%1$dx Ereignisse in %2$@"
        ],

        .english: [
            "app_name": "CRISIS 2050",
            "tab_overview": "Overview",
            "tab_comparison": "Comparison",
            "tab_metals": "Metals",
            "tab_crisis": "Crises",
            "tab_consultation": "Consultation",
            "cta_title": "Request consultation",
            "cta_subtitle": "Secure your wealth with precious metals",
            "overview_title": "Overview",
            "overview_hero_title": "Wealth protection",
            "overview_hero_subtitle": "Current outlook",
            "overview_forecast_label": "Forecast",
            "overview_forecast_hint": "Caution advised - prioritize protection.",
            "overview_metals_focus": "Precious metals in focus",
            "overview_metals_focus_subtitle": "Gold & Silver in the current market environment",
            "overview_macro_title": "Macro outlook",
            "overview_macro_subtitle": "Inflation, FX & growth by region",
            "why_metals_title": "Why precious metals and structure",
            "why_metals_bullet_1": "Physical value, independent of currencies",
            "why_metals_bullet_2": "Protection against inflation and purchasing power loss",
            "why_metals_bullet_3": "Stability in wars and economic crises",
            "why_metals_bullet_4": "Structured wealth protection through planned allocation",
            "why_metals_bullet_5": "Secure storage in bonded warehouse outside the banking system",
            "comparison_title": "Comparison",
            "comparison_section_title": "Asset class comparison",
            "comparison_section_subtitle": "History & forecast 2025–2050",
            "comparison_period": "Period",
            "comparison_mode_history": "History",
            "comparison_mode_forecast": "Forecast",
            "comparison_chart_title": "Value development",
            "comparison_chart_subtitle": "Tap the chart to see details.",
            "comparison_performance_title": "Performance overview",
            "comparison_performance_subtitle": "History and forecast",
            "comparison_no_data": "No market data available.",
            "comparison_loading": "Loading market data…",
            "comparison_macro_title": "Macro comparison",
            "comparison_macro_subtitle": "Regional trends side by side",
            "comparison_macro_loading": "Loading macro data.",
            "comparison_macro_no_data": "No macro data available.",
            "comparison_scenario_title": "Scenario lab",
            "comparison_scenario_subtitle": "Adjust inflation, growth and defense",
            "comparison_scenario_inflation": "Inflation (%)",
            "comparison_scenario_growth": "Growth (%)",
            "comparison_scenario_defense": "Defense (%% GDP)",
            "comparison_scenario_equities": "Equities",
            "comparison_scenario_real_estate": "Real estate",
            "comparison_scenario_metals": "Precious metals",
            "comparison_portfolio_title": "Portfolio resilience",
            "comparison_portfolio_subtitle": "Mix of equities, real estate and precious metals",
            "metals_title": "Precious metals",
            "metals_selector_title": "Select precious metal",
            "metals_projection_title": "3-year forecast",
            "metals_projection_subtitle": "%1$@ outlook",
            "metals_trend_title": "History & forecast to 2050",
            "metals_trend_subtitle": "Index performance %1$@",
            "metals_trend_loading": "Loading market data…",
            "metals_resilience_title": "Resilience in crises",
            "metals_resilience_subtitle": "%1$@ across different scenarios",
            "metals_scenario_inflation": "Inflation",
            "metals_scenario_wars": "Wars",
            "metals_scenario_wars_detail": "Geopolitical tensions increase demand for safe havens.",
            "metals_scenario_recession": "Recessions",
            "metals_scenario_recession_detail": "In recessions, %1$@ serves as a liquidity reserve.",
            "metals_badge_protection": "Protection",
            "metals_badge_shield": "Hedge",
            "metals_badge_diversification": "Diversification",
            "crisis_title": "Crises",
            "crisis_overview_title": "Crisis situation",
            "crisis_overview_subtitle": "Current signals from external sources",
            "crisis_overview_empty": "No current signals.",
            "crisis_feed_title": "Crisis feed",
            "crisis_feed_subtitle": "Updates from NewsAPI and the World Bank",
            "crisis_feed_empty": "No current crisis reports.",
            "crisis_category_financial": "Financial",
            "crisis_category_geopolitical": "Geopolitics",
            "crisis_badge_info": "Info",
            "crisis_badge_moderate": "Moderate",
            "crisis_badge_high": "High",
            "crisis_detail_title": "Crisis details",
            "crisis_detail_missing": "Event not found.",
            "crisis_detail_time": "Time: %1$@",
            "crisis_detail_source": "Source: %1$@",
            "crisis_detail_open_source": "Open source",
            "crisis_detail_timeline_title": "Timeline",
            "consultation_title": "Request consultation",
            "consultation_panel_subtitle": "For personal advice, please use the contact form on the website.",
            "consultation_section_expectations": "What to expect",
            "consultation_expectation_1": "Free initial consultation with precious metals experts",
            "consultation_expectation_2": "Individual wealth structuring",
            "consultation_expectation_3": "Information about bonded warehouse storage",
            "consultation_expectation_4": "Tax aspects and legal protection",
            "consultation_section_contact": "Your contact details",
            "consultation_section_message": "Message",
            "consultation_name": "Name*",
            "consultation_email": "Email*",
            "consultation_phone": "Phone*",
            "consultation_message_hint": "How can we help you?*",
            "consultation_submit": "Send request",
            "consultation_submit_success_title": "Thank you",
            "consultation_submit_success_message": "Your request was sent. We will get back to you soon.",
            "consultation_submit_failure_title": "Send failed",
            "consultation_submit_failure_message": "Failed to send the request.",
            "consultation_privacy_note": "By submitting, you agree that we respond to your request in accordance with the privacy policy. We do not store any data permanently on this device.",
            "consultation_error_name": "Please enter your name.",
            "consultation_error_email": "Please enter a valid email address.",
            "consultation_error_phone": "Please enter your phone number.",
            "consultation_error_message": "Your message should be at least 10 characters.",
            "consultation_error_invalid": "Invalid input",
            "consultation_section_more_info": "More information",
            "consultation_info_1_title": "Bonded warehouse storage",
            "consultation_info_1_text": "Physical separation from the banking system, insurance, and 24/7 monitoring for maximum security and flexibility.",
            "consultation_info_2_title": "Value - structure wins",
            "consultation_info_2_text": "Clear allocation in precious metals creates stability in inflation, currency reforms, and crises.",
            "settings_title": "Settings",
            "settings_section_general": "General",
            "settings_currency_label": "Display currency",
            "settings_currency_hint": "Controls which currency precious metal prices are shown in throughout the interface.",
            "settings_watchlist_section": "Crisis watchlist",
            "settings_watchlist_geopolitical": "Geopolitics",
            "settings_watchlist_financial": "Business cycle",
            "settings_thresholds_section": "Crisis thresholds",
            "settings_thresholds_label": "Sensitivity",
            "settings_thresholds_standard": "Standard",
            "settings_thresholds_sensitive": "Sensitive",
            "settings_thresholds_conservative": "Conservative",
            "settings_thresholds_hint": "Influences when events are marked as high risk.",
            "settings_notifications_section": "Notifications",
            "settings_notifications_label": "Notifications",
            "settings_privacy_section": "Consultation & privacy",
            "settings_privacy_policy": "Privacy policy",
            "settings_privacy_note": "Personal data leaves your device only when you send a request. No data is stored locally.",
            "settings_transparency_note": "All economic data comes from open APIs by GoldPrice.org and the World Bank.",
            "settings_contact_note": "Use the Consultation tab for individual questions. Responses are GDPR-compliant by email.",
            "settings_done": "Done",
            "notifications_status_active": "Active",
            "notifications_status_denied": "Disabled",
            "notifications_status_limited": "Limited",
            "notifications_status_unknown": "Unknown",
            "notifications_description_active": "You will receive alerts for forecast changes or major crises.",
            "notifications_description_denied": "Notifications are turned off. Enable them in system settings.",
            "notifications_description_limited": "Temporary permission - confirm it to keep critical alerts.",
            "notifications_description_undetermined": "No permission requested yet.",
            "notifications_action_open_settings": "Open system settings",
            "notifications_action_enable": "Enable notifications",
            "notifications_action_adjust": "Confirm permission",
            "notification_onboarding_title": "Notifications",
            "notification_onboarding_headline": "Crisis alerts",
            "notification_onboarding_body": "Receive one-time push alerts for high-risk events. We only send notifications when the situation is serious.",
            "notification_onboarding_toggle_title": "Real-time notifications",
            "notification_onboarding_toggle_hint": "Only crises with severity 5+ and no ads.",
            "notification_onboarding_device_hint": "You can change your decision anytime in system settings.",
            "notification_onboarding_privacy_hint": "No data leaves your device. Basis: App Store Guideline 5.1.1.",
            "notification_onboarding_enable": "Enable crisis alerts",
            "notification_onboarding_later": "Maybe later",
            "notification_onboarding_error_toggle": "Enable the toggle to allow notifications.",
            "notification_onboarding_error_settings": "Please allow notifications in system settings.",
            "notification_banner_denied": "Crisis alerts disabled",
            "notification_banner_limited": "Crisis alerts in quiet mode",
            "notification_banner_missing": "Crisis alerts not enabled yet",
            "notification_banner_message_denied": "Enable notifications to see acute crises immediately.",
            "notification_banner_message_limited": "App notifications are currently delivered silently. Enable banners/sounds.",
            "notification_banner_message_missing": "Tap here to enable push alerts for high-risk situations.",
            "notification_banner_action_settings": "Open settings",
            "notification_banner_action_adjust": "Adjust settings",
            "privacy_policy_title": "Privacy policy",
            "privacy_policy_website": "Website",
            "privacy_policy_intro": "We process your data only on the device or when sending your request. There are no hidden trackers or cloud profiles.",
            "privacy_section_controller_title": "Responsible entity",
            "privacy_section_controller_body": "VermögensKompass (Vibecode GmbH) processes only the data you actively share.",
            "privacy_section_collection_title": "Data collection at a glance",
            "privacy_section_collection_body": "• Market and crisis data comes from publicly available APIs (World Bank, USGS, NOAA, GoldPrice.org) and is evaluated locally only.\n• We do not store personal data on our servers.",
            "privacy_section_contact_title": "Contact",
            "privacy_section_contact_body": "When you tap “Request consultation”, we send your message to our advisory team. Transmission is via a secure connection; we do not store a copy.",
            "privacy_section_notifications_title": "Notifications",
            "privacy_section_notifications_body": "Crisis notifications are processed only on your device. You can revoke permission at any time in system settings.",
            "privacy_section_tracking_title": "Analytics & Tracking",
            "privacy_section_tracking_body": "No tracking, no third-party SDKs. The app works fully offline with the last synchronized data.",
            "privacy_section_rights_title": "Your rights",
            "privacy_section_rights_body": "You can request access, correction or deletion of your contact submission by contacting us at datenschutz@vermoegenskompass.de.",
            "offline_banner_title": "Offline data",
            "offline_banner_no_sync": "No successful synchronization yet",
            "crisis_notification_channel": "Crisis alerts",
            "crisis_notification_title": "Crisis situation: %1$@",
            "crisis_notification_body": "Region: %1$@. Category: %2$@.",
            "generic_ok": "OK",
            "error_loading": "Error while loading",
            "sync_error_background_update": "Background update failed",
            "async_loading": "Updating data.",
            "async_retry": "Try again",
            "sync_last_successful": "Last sync: %1$@",
            "sync_never_successful": "No successful sync yet",
            "consultation_submit_loading": "Sending…",
            "not_available_short": "N/A",
            "comparison_performance_format": "History %1$@ / Forecast %2$@",
            "comparison_chart_today": "Today",
            "comparison_chart_x_label": "Year",
            "comparison_chart_y_label": "Value in %1$@",
            "macro_delta_no_trend": "No trend",
            "macro_delta_vs_previous": "%1$@%2$@%3$@ vs. previous year",
            "macro_region_de": "DE",
            "macro_region_us": "US",
            "macro_region_uk": "UK",
            "macro_region_es": "ES",
            "currency_eur": "Euro (€)",
            "currency_usd": "US dollar ($)",
            "settings_language_section": "Language",
            "settings_language_label": "App language",
            "settings_language_hint": "Changes the interface language.",
            "language_de": "German",
            "language_en": "English",
            "language_fr": "French",
            "language_es": "Spanish",
            "metal_insight_24h": "24h",
            "metal_insight_change": "Change",
            "metal_source_label": "Source: %1$@",
            "metals_scenario_inflation_detail": "%1$@ historically reacts positively to rising consumer prices.",
            "asset_group_equities": "Equity markets",
            "asset_group_real_estate": "Real estate prices",
            "asset_group_metals": "Precious metals",
            "asset_equity_de": "Germany equities",
            "asset_equity_usa": "US equities",
            "asset_equity_lon": "London equities",
            "asset_real_estate_de": "Germany real estate",
            "asset_real_estate_es": "Spain real estate",
            "asset_real_estate_fr": "France real estate",
            "asset_real_estate_lon": "London real estate",
            "asset_gold": "Gold",
            "asset_silver": "Silver",
            "macro_indicator_inflation_title": "Inflation",
            "macro_indicator_inflation_description": "Annual consumer price inflation (World Bank)",
            "macro_indicator_inflation_unit": "%",
            "macro_indicator_growth_title": "Growth",
            "macro_indicator_growth_description": "Real GDP growth",
            "macro_indicator_growth_unit": "%",
            "macro_indicator_defense_title": "Defense",
            "macro_indicator_defense_description": "Military expenditure as a share of GDP",
            "macro_indicator_defense_unit": "% GDP",
            "benner_phase_panic_title": "Panic year",
            "benner_phase_panic_subtitle": "Extreme selling pressure - Phase A",
            "benner_phase_panic_guidance": "Historically, these years were followed by sharp market declines. Secure liquidity and limit risk.",
            "benner_phase_good_title": "Good times",
            "benner_phase_good_subtitle": "High prices - Phase B (prefer selling)",
            "benner_phase_good_guidance": "Above-average valuations. Lock in gains and reduce exposure.",
            "benner_phase_hard_title": "Hard times",
            "benner_phase_hard_subtitle": "Low prices - Phase C (accumulation)",
            "benner_phase_hard_guidance": "Prices are considered attractive. Building positions and savings plans are recommended.",
            "benner_entry_summary": "%1$d - %2$@",
            "watchlist_country_ukraine": "Ukraine",
            "watchlist_country_israel": "Israel",
            "watchlist_country_taiwan": "Taiwan",
            "watchlist_country_south_africa": "South Africa",
            "watchlist_country_germany": "Germany",
            "watchlist_country_usa": "United States",
            "watchlist_country_uk": "United Kingdom",
            "watchlist_country_japan": "Japan",
            "watchlist_country_china": "China",
            "crisis_summary_headline_none": "No high-risk events detected",
            "crisis_summary_highlight_category": "%1$dx category %2$@",
            "crisis_summary_highlight_latest": "Latest %1$@ at %2$@",
            "crisis_event_title_governance": "Political instability in %1$@",
            "crisis_event_title_recession": "Recession in %1$@",
            "crisis_summary_headline_count_one": "%d high-risk event active",
            "crisis_summary_headline_count_other": "%d high-risk events active",
            "crisis_summary_highlight_region_one": "%1$dx event in %2$@",
            "crisis_summary_highlight_region_other": "%1$dx events in %2$@"
        ],

        .french: [
            "app_name": "CRISIS 2050",
            "tab_overview": "Aperçu",
            "tab_comparison": "Comparaison",
            "tab_metals": "Métaux précieux",
            "tab_crisis": "Crises",
            "tab_consultation": "Conseil",
            "cta_title": "Demander un conseil",
            "cta_subtitle": "Protégez votre patrimoine avec les métaux précieux",
            "overview_title": "Aperçu",
            "overview_hero_title": "Protection du patrimoine",
            "overview_hero_subtitle": "Projection actuelle",
            "overview_forecast_label": "Prévision",
            "overview_forecast_hint": "Prudence recommandée - prioriser la protection.",
            "overview_metals_focus": "Métaux précieux au premier plan",
            "overview_metals_focus_subtitle": "Or & Argent dans le contexte de marché actuel",
            "overview_macro_title": "Vue macro",
            "overview_macro_subtitle": "Inflation, change & croissance par région",
            "why_metals_title": "Pourquoi les métaux précieux et la structure",
            "why_metals_bullet_1": "Valeur physique, indépendante des devises",
            "why_metals_bullet_2": "Protection contre l’inflation et la perte de pouvoir d’achat",
            "why_metals_bullet_3": "Stabilité en temps de guerre et de crise économique",
            "why_metals_bullet_4": "Protection patrimoniale structurée par une allocation planifiée",
            "why_metals_bullet_5": "Stockage sécurisé en entrepôt sous douane hors du système bancaire",
            "comparison_title": "Comparaison",
            "comparison_section_title": "Comparaison des classes d’actifs",
            "comparison_section_subtitle": "Historique & prévision 2025–2050",
            "comparison_period": "Période",
            "comparison_mode_history": "Historique",
            "comparison_mode_forecast": "Prévision",
            "comparison_chart_title": "Évolution de la valeur",
            "comparison_chart_subtitle": "Touchez le graphique pour voir les détails.",
            "comparison_performance_title": "Aperçu des performances",
            "comparison_performance_subtitle": "Historique et prévision",
            "comparison_no_data": "Aucune donnée de marché disponible.",
            "comparison_loading": "Chargement des données de marché…",
            "comparison_macro_title": "Comparaison macro",
            "comparison_macro_subtitle": "Tendances régionales côte à côte",
            "comparison_macro_loading": "Chargement des données macro.",
            "comparison_macro_no_data": "Aucune donnée macro disponible.",
            "comparison_scenario_title": "Laboratoire de scénario",
            "comparison_scenario_subtitle": "Ajuster inflation, croissance et défense",
            "comparison_scenario_inflation": "Inflation (%)",
            "comparison_scenario_growth": "Croissance (%)",
            "comparison_scenario_defense": "Défense (%% PIB)",
            "comparison_scenario_equities": "Actions",
            "comparison_scenario_real_estate": "Immobilier",
            "comparison_scenario_metals": "Métaux précieux",
            "comparison_portfolio_title": "Résilience du portefeuille",
            "comparison_portfolio_subtitle": "Mix d’actions, d’immobilier et de métaux précieux",
            "metals_title": "Métaux précieux",
            "metals_selector_title": "Choisir un métal précieux",
            "metals_projection_title": "Prévision sur 3 ans",
            "metals_projection_subtitle": "Perspectives %1$@",
            "metals_trend_title": "Historique & prévision jusqu’à 2050",
            "metals_trend_subtitle": "Performance de l’indice %1$@",
            "metals_trend_loading": "Chargement des données de marché…",
            "metals_resilience_title": "Résilience en crise",
            "metals_resilience_subtitle": "%1$@ dans différents scénarios",
            "metals_scenario_inflation": "Inflation",
            "metals_scenario_wars": "Guerres",
            "metals_scenario_wars_detail": "Les tensions géopolitiques augmentent la demande pour les valeurs refuges.",
            "metals_scenario_recession": "Récessions",
            "metals_scenario_recession_detail": "En récession, %1$@ sert de réserve de liquidité.",
            "metals_badge_protection": "Protection",
            "metals_badge_shield": "Couverture",
            "metals_badge_diversification": "Diversification",
            "crisis_title": "Crises",
            "crisis_overview_title": "Situation de crise",
            "crisis_overview_subtitle": "Signaux actuels provenant de sources externes",
            "crisis_overview_empty": "Aucun signal actuel.",
            "crisis_feed_title": "Flux de crise",
            "crisis_feed_subtitle": "Actualités de NewsAPI et de la Banque mondiale",
            "crisis_feed_empty": "Aucune actualité de crise.",
            "crisis_category_financial": "Finance",
            "crisis_category_geopolitical": "Géopolitique",
            "crisis_badge_info": "Info",
            "crisis_badge_moderate": "Modéré",
            "crisis_badge_high": "Élevé",
            "crisis_detail_title": "Détails de la crise",
            "crisis_detail_missing": "Événement introuvable.",
            "crisis_detail_time": "Date : %1$@",
            "crisis_detail_source": "Source : %1$@",
            "crisis_detail_open_source": "Ouvrir la source",
            "crisis_detail_timeline_title": "Chronologie",
            "consultation_title": "Demander un conseil",
            "consultation_panel_subtitle": "Pour un conseil personnalisé, veuillez utiliser le formulaire de contact sur le site web.",
            "consultation_section_expectations": "Ce qui vous attend",
            "consultation_expectation_1": "Première consultation gratuite avec des experts en métaux précieux",
            "consultation_expectation_2": "Structuration patrimoniale personnalisée",
            "consultation_expectation_3": "Informations sur le stockage en entrepôt sous douane",
            "consultation_expectation_4": "Aspects fiscaux et protection juridique",
            "consultation_section_contact": "Vos coordonnées",
            "consultation_section_message": "Message",
            "consultation_name": "Nom*",
            "consultation_email": "E-mail*",
            "consultation_phone": "Téléphone*",
            "consultation_message_hint": "Comment pouvons-nous vous aider ?*",
            "consultation_submit": "Envoyer la demande",
            "consultation_submit_success_title": "Merci",
            "consultation_submit_success_message": "Votre demande a été envoyée. Nous revenons vers vous rapidement.",
            "consultation_submit_failure_title": "Échec de l’envoi",
            "consultation_submit_failure_message": "Échec de l’envoi de la demande.",
            "consultation_privacy_note": "En envoyant, vous acceptez que nous répondions à votre demande conformément à la politique de confidentialité. Nous ne stockons aucune donnée sur cet appareil.",
            "consultation_error_name": "Veuillez indiquer votre nom.",
            "consultation_error_email": "Veuillez saisir une adresse e-mail valide.",
            "consultation_error_phone": "Veuillez indiquer votre numéro de téléphone.",
            "consultation_error_message": "Votre message doit comporter au moins 10 caractères.",
            "consultation_error_invalid": "Saisie invalide",
            "consultation_section_more_info": "Plus d’informations",
            "consultation_info_1_title": "Stockage en entrepôt sous douane",
            "consultation_info_1_text": "Séparation physique du système bancaire, assurance et surveillance 24/7 pour une sécurité et une flexibilité maximales.",
            "consultation_info_2_title": "La valeur - la structure gagne",
            "consultation_info_2_text": "Une allocation claire en métaux précieux crée de la stabilité en période d’inflation, de réformes monétaires et de crises.",
            "settings_title": "Paramètres",
            "settings_section_general": "Général",
            "settings_currency_label": "Devise d’affichage",
            "settings_currency_hint": "Détermine dans quelle devise les prix des métaux précieux sont affichés dans l’interface.",
            "settings_watchlist_section": "Liste de surveillance des crises",
            "settings_watchlist_geopolitical": "Géopolitique",
            "settings_watchlist_financial": "Conjoncture",
            "settings_thresholds_section": "Seuils de crise",
            "settings_thresholds_label": "Sensibilité",
            "settings_thresholds_standard": "Standard",
            "settings_thresholds_sensitive": "Sensible",
            "settings_thresholds_conservative": "Conservateur",
            "settings_thresholds_hint": "Influence quand un événement est marqué à haut risque.",
            "settings_notifications_section": "Notifications",
            "settings_notifications_label": "Notifications",
            "settings_privacy_section": "Conseil & confidentialité",
            "settings_privacy_policy": "Politique de confidentialité",
            "settings_privacy_note": "Les données personnelles quittent votre appareil uniquement si vous envoyez une demande. Aucun stockage local.",
            "settings_transparency_note": "Toutes les données économiques proviennent d’API ouvertes de GoldPrice.org et de la Banque mondiale.",
            "settings_contact_note": "Utilisez l’onglet Conseil pour des questions individuelles. Les réponses sont conformes au RGPD par e-mail.",
            "settings_done": "Terminé",
            "notifications_status_active": "Actif",
            "notifications_status_denied": "Désactivé",
            "notifications_status_limited": "Limité",
            "notifications_status_unknown": "Inconnu",
            "notifications_description_active": "Vous recevez des alertes lors des changements de prévision ou de crises majeures.",
            "notifications_description_denied": "Les notifications sont désactivées. Activez-les dans les paramètres système.",
            "notifications_description_limited": "Autorisation temporaire - confirmez-la pour conserver les alertes critiques.",
            "notifications_description_undetermined": "Aucune autorisation demandée pour le moment.",
            "notifications_action_open_settings": "Ouvrir les paramètres système",
            "notifications_action_enable": "Activer les notifications",
            "notifications_action_adjust": "Confirmer l’autorisation",
            "notification_onboarding_title": "Notifications",
            "notification_onboarding_headline": "Alertes de crise",
            "notification_onboarding_body": "Recevez des alertes push uniques pour les événements à haut risque. Nous n’envoyons des notifications que si la situation est grave.",
            "notification_onboarding_toggle_title": "Notifications en temps réel",
            "notification_onboarding_toggle_hint": "Uniquement les crises de gravité 5+ et aucune publicité.",
            "notification_onboarding_device_hint": "Vous pouvez modifier votre décision à tout moment dans les paramètres système.",
            "notification_onboarding_privacy_hint": "Aucune donnée ne quitte votre appareil. Base : App Store Guideline 5.1.1.",
            "notification_onboarding_enable": "Activer les alertes de crise",
            "notification_onboarding_later": "Peut-être plus tard",
            "notification_onboarding_error_toggle": "Activez l’interrupteur pour autoriser les notifications.",
            "notification_onboarding_error_settings": "Veuillez autoriser les notifications dans les paramètres système.",
            "notification_banner_denied": "Alertes de crise désactivées",
            "notification_banner_limited": "Alertes de crise en mode silencieux",
            "notification_banner_missing": "Alertes de crise non activées",
            "notification_banner_message_denied": "Activez les notifications pour voir immédiatement les crises urgentes.",
            "notification_banner_message_limited": "Les notifications de l’application sont actuellement silencieuses. Activez bannières/sons.",
            "notification_banner_message_missing": "Appuyez ici pour activer les alertes push en cas de risque élevé.",
            "notification_banner_action_settings": "Ouvrir les paramètres",
            "notification_banner_action_adjust": "Ajuster les paramètres",
            "privacy_policy_title": "Politique de confidentialité",
            "privacy_policy_website": "Site web",
            "privacy_policy_intro": "Nous traitons vos données uniquement sur l’appareil ou lors de l’envoi de votre demande. Aucun traceur caché ni profil cloud.",
            "privacy_section_controller_title": "Responsable",
            "privacy_section_controller_body": "VermögensKompass (Vibecode GmbH) traite uniquement les données que vous partagez activement.",
            "privacy_section_collection_title": "Collecte des données en bref",
            "privacy_section_collection_body": "• Les données de marché et de crise proviennent d’API publiques (World Bank, USGS, NOAA, GoldPrice.org) et sont évaluées localement.\n• Nous ne stockons pas de données personnelles sur nos serveurs.",
            "privacy_section_contact_title": "Contact",
            "privacy_section_contact_body": "Lorsque vous appuyez sur « Demander un conseil », nous envoyons votre message à notre équipe de conseil. L’envoi se fait via une connexion sécurisée ; nous n’en conservons pas de copie.",
            "privacy_section_notifications_title": "Notifications",
            "privacy_section_notifications_body": "Les notifications de crise sont traitées uniquement sur votre appareil. Vous pouvez révoquer l’autorisation à tout moment dans les paramètres système.",
            "privacy_section_tracking_title": "Analytics & Tracking",
            "privacy_section_tracking_body": "Aucun tracking, aucun SDK tiers. L’application fonctionne entièrement hors ligne avec les dernières données synchronisées.",
            "privacy_section_rights_title": "Vos droits",
            "privacy_section_rights_body": "Vous pouvez demander l’accès, la rectification ou la suppression de votre prise de contact en nous écrivant à datenschutz@vermoegenskompass.de.",
            "offline_banner_title": "Données hors ligne",
            "offline_banner_no_sync": "Aucune synchronisation réussie",
            "crisis_notification_channel": "Alertes de crise",
            "crisis_notification_title": "Situation de crise : %1$@",
            "crisis_notification_body": "Région : %1$@. Catégorie : %2$@.",
            "generic_ok": "OK",
            "error_loading": "Erreur lors du chargement",
            "sync_error_background_update": "Échec de la mise à jour en arrière-plan",
            "async_loading": "Mise à jour des données.",
            "async_retry": "Réessayer",
            "sync_last_successful": "Dernière synchronisation : %1$@",
            "sync_never_successful": "Aucune synchronisation réussie",
            "consultation_submit_loading": "Envoi…",
            "not_available_short": "N/D",
            "comparison_performance_format": "Historique %1$@ / Prévision %2$@",
            "comparison_chart_today": "Aujourd’hui",
            "comparison_chart_x_label": "Année",
            "comparison_chart_y_label": "Valeur en %1$@",
            "macro_delta_no_trend": "Pas de tendance",
            "macro_delta_vs_previous": "%1$@%2$@%3$@ vs. année précédente",
            "macro_region_de": "DE",
            "macro_region_us": "US",
            "macro_region_uk": "UK",
            "macro_region_es": "ES",
            "currency_eur": "Euro (€)",
            "currency_usd": "Dollar américain ($)",
            "settings_language_section": "Langue",
            "settings_language_label": "Langue de l’application",
            "settings_language_hint": "Modifie la langue de l’interface.",
            "language_de": "Allemand",
            "language_en": "Anglais",
            "language_fr": "Français",
            "language_es": "Espagnol",
            "metal_insight_24h": "24h",
            "metal_insight_change": "Variation",
            "metal_source_label": "Source : %1$@",
            "metals_scenario_inflation_detail": "%1$@ réagit historiquement positivement à la hausse des prix à la consommation.",
            "asset_group_equities": "Marchés actions",
            "asset_group_real_estate": "Prix immobiliers",
            "asset_group_metals": "Métaux précieux",
            "asset_equity_de": "Actions Allemagne",
            "asset_equity_usa": "Actions États-Unis",
            "asset_equity_lon": "Actions Londres",
            "asset_real_estate_de": "Immobilier Allemagne",
            "asset_real_estate_es": "Immobilier Espagne",
            "asset_real_estate_fr": "Immobilier France",
            "asset_real_estate_lon": "Immobilier Londres",
            "asset_gold": "Or",
            "asset_silver": "Argent",
            "macro_indicator_inflation_title": "Inflation",
            "macro_indicator_inflation_description": "Inflation annuelle des prix à la consommation (Banque mondiale)",
            "macro_indicator_inflation_unit": "%",
            "macro_indicator_growth_title": "Croissance",
            "macro_indicator_growth_description": "Croissance réelle du PIB",
            "macro_indicator_growth_unit": "%",
            "macro_indicator_defense_title": "Défense",
            "macro_indicator_defense_description": "Dépenses militaires en % du PIB",
            "macro_indicator_defense_unit": "% PIB",
            "benner_phase_panic_title": "Année de panique",
            "benner_phase_panic_subtitle": "Pression de vente extrême - Phase A",
            "benner_phase_panic_guidance": "Historiquement, ces années ont été suivies de fortes baisses. Sécuriser la liquidité et limiter le risque.",
            "benner_phase_good_title": "Bonnes périodes",
            "benner_phase_good_subtitle": "Prix élevés - Phase B (privilégier les ventes)",
            "benner_phase_good_guidance": "Valorisations supérieures à la moyenne. Sécuriser les gains et réduire l’exposition.",
            "benner_phase_hard_title": "Périodes difficiles",
            "benner_phase_hard_subtitle": "Prix bas - Phase C (accumulation)",
            "benner_phase_hard_guidance": "Les prix sont jugés attractifs. Constitution de positions et plans d’épargne recommandés.",
            "benner_entry_summary": "%1$d - %2$@",
            "watchlist_country_ukraine": "Ukraine",
            "watchlist_country_israel": "Israël",
            "watchlist_country_taiwan": "Taïwan",
            "watchlist_country_south_africa": "Afrique du Sud",
            "watchlist_country_germany": "Allemagne",
            "watchlist_country_usa": "États-Unis",
            "watchlist_country_uk": "Royaume-Uni",
            "watchlist_country_japan": "Japon",
            "watchlist_country_china": "Chine",
            "crisis_summary_headline_none": "Aucun événement à haut risque détecté",
            "crisis_summary_highlight_category": "%1$dx catégorie %2$@",
            "crisis_summary_highlight_latest": "Dernier : %1$@ à %2$@",
            "crisis_event_title_governance": "Instabilité politique en %1$@",
            "crisis_event_title_recession": "Récession en %1$@",
            "crisis_summary_headline_count_one": "%d événement à haut risque actif",
            "crisis_summary_headline_count_other": "%d événements à haut risque actifs",
            "crisis_summary_highlight_region_one": "%1$dx événement en %2$@",
            "crisis_summary_highlight_region_other": "%1$dx événements en %2$@"
        ],

        .spanish: [
            "app_name": "CRISIS 2050",
            "tab_overview": "Resumen",
            "tab_comparison": "Comparación",
            "tab_metals": "Metales preciosos",
            "tab_crisis": "Crisis",
            "tab_consultation": "Asesoría",
            "cta_title": "Solicitar asesoría",
            "cta_subtitle": "Proteja su patrimonio con metales preciosos",
            "overview_title": "Resumen",
            "overview_hero_title": "Protección del patrimonio",
            "overview_hero_subtitle": "Pronóstico actual",
            "overview_forecast_label": "Pronóstico",
            "overview_forecast_hint": "Se recomienda precaución - priorice la protección.",
            "overview_metals_focus": "Metales preciosos en foco",
            "overview_metals_focus_subtitle": "Oro & Plata en el contexto de mercado actual",
            "overview_macro_title": "Panorama macro",
            "overview_macro_subtitle": "Inflación, tipo de cambio y crecimiento por región",
            "why_metals_title": "Por qué metales preciosos y estructura",
            "why_metals_bullet_1": "Valor físico, independiente de las monedas",
            "why_metals_bullet_2": "Protección contra la inflación y la pérdida de poder adquisitivo",
            "why_metals_bullet_3": "Estabilidad en guerras y crisis económicas",
            "why_metals_bullet_4": "Protección patrimonial estructurada mediante una asignación planificada",
            "why_metals_bullet_5": "Almacenamiento seguro en depósito aduanero fuera del sistema bancario",
            "comparison_title": "Comparación",
            "comparison_section_title": "Comparación de clases de activos",
            "comparison_section_subtitle": "Histórico y pronóstico 2025–2050",
            "comparison_period": "Periodo",
            "comparison_mode_history": "Histórico",
            "comparison_mode_forecast": "Pronóstico",
            "comparison_chart_title": "Evolución del valor",
            "comparison_chart_subtitle": "Toque el gráfico para ver detalles.",
            "comparison_performance_title": "Resumen de rendimiento",
            "comparison_performance_subtitle": "Histórico y pronóstico",
            "comparison_no_data": "No hay datos de mercado disponibles.",
            "comparison_loading": "Cargando datos de mercado…",
            "comparison_macro_title": "Comparación macro",
            "comparison_macro_subtitle": "Tendencias regionales lado a lado",
            "comparison_macro_loading": "Cargando datos macro.",
            "comparison_macro_no_data": "No hay datos macro disponibles.",
            "comparison_scenario_title": "Laboratorio de escenarios",
            "comparison_scenario_subtitle": "Ajustar inflación, crecimiento y defensa",
            "comparison_scenario_inflation": "Inflación (%)",
            "comparison_scenario_growth": "Crecimiento (%)",
            "comparison_scenario_defense": "Defensa (%% PIB)",
            "comparison_scenario_equities": "Acciones",
            "comparison_scenario_real_estate": "Inmobiliario",
            "comparison_scenario_metals": "Metales preciosos",
            "comparison_portfolio_title": "Resiliencia del portafolio",
            "comparison_portfolio_subtitle": "Mezcla de acciones, inmobiliario y metales preciosos",
            "metals_title": "Metales preciosos",
            "metals_selector_title": "Seleccionar metal precioso",
            "metals_projection_title": "Pronóstico a 3 años",
            "metals_projection_subtitle": "Perspectiva de %1$@",
            "metals_trend_title": "Histórico y pronóstico hasta 2050",
            "metals_trend_subtitle": "Evolución del índice %1$@",
            "metals_trend_loading": "Cargando datos de mercado…",
            "metals_resilience_title": "Resiliencia en crisis",
            "metals_resilience_subtitle": "%1$@ en distintos escenarios",
            "metals_scenario_inflation": "Inflación",
            "metals_scenario_wars": "Guerras",
            "metals_scenario_wars_detail": "Las tensiones geopolíticas aumentan la demanda de activos refugio.",
            "metals_scenario_recession": "Recesiones",
            "metals_scenario_recession_detail": "En recesiones, %1$@ actúa como reserva de liquidez.",
            "metals_badge_protection": "Protección",
            "metals_badge_shield": "Cobertura",
            "metals_badge_diversification": "Diversificación",
            "crisis_title": "Crisis",
            "crisis_overview_title": "Situación de crisis",
            "crisis_overview_subtitle": "Señales actuales de fuentes externas",
            "crisis_overview_empty": "No hay señales actuales.",
            "crisis_feed_title": "Feed de crisis",
            "crisis_feed_subtitle": "Noticias de NewsAPI y del Banco Mundial",
            "crisis_feed_empty": "No hay noticias de crisis actuales.",
            "crisis_category_financial": "Finanzas",
            "crisis_category_geopolitical": "Geopolítica",
            "crisis_badge_info": "Info",
            "crisis_badge_moderate": "Moderado",
            "crisis_badge_high": "Alto",
            "crisis_detail_title": "Detalles de la crisis",
            "crisis_detail_missing": "Evento no encontrado.",
            "crisis_detail_time": "Momento: %1$@",
            "crisis_detail_source": "Fuente: %1$@",
            "crisis_detail_open_source": "Abrir fuente",
            "crisis_detail_timeline_title": "Línea de tiempo",
            "consultation_title": "Solicitar asesoría",
            "consultation_panel_subtitle": "Para un asesoramiento personalizado, utilice el formulario de contacto en el sitio web.",
            "consultation_section_expectations": "Qué puede esperar",
            "consultation_expectation_1": "Primera asesoría gratuita con expertos en metales preciosos",
            "consultation_expectation_2": "Estructuración patrimonial individual",
            "consultation_expectation_3": "Información sobre almacenamiento en depósito aduanero",
            "consultation_expectation_4": "Aspectos fiscales y protección legal",
            "consultation_section_contact": "Sus datos de contacto",
            "consultation_section_message": "Mensaje",
            "consultation_name": "Nombre*",
            "consultation_email": "Correo electrónico*",
            "consultation_phone": "Teléfono*",
            "consultation_message_hint": "¿Cómo podemos ayudarle?*",
            "consultation_submit": "Enviar solicitud",
            "consultation_submit_success_title": "Gracias",
            "consultation_submit_success_message": "Su solicitud fue enviada. Nos pondremos en contacto pronto.",
            "consultation_submit_failure_title": "Envío fallido",
            "consultation_submit_failure_message": "Error al enviar la solicitud.",
            "consultation_privacy_note": "Al enviar, acepta que respondamos a su solicitud conforme a la política de privacidad. No almacenamos datos de forma permanente en este dispositivo.",
            "consultation_error_name": "Por favor, indique su nombre.",
            "consultation_error_email": "Por favor, introduzca una dirección de correo válida.",
            "consultation_error_phone": "Por favor, indique su número de teléfono.",
            "consultation_error_message": "Su mensaje debe tener al menos 10 caracteres.",
            "consultation_error_invalid": "Entrada no válida",
            "consultation_section_more_info": "Más información",
            "consultation_info_1_title": "Almacenamiento en depósito aduanero",
            "consultation_info_1_text": "Separación física del sistema bancario, seguro y vigilancia 24/7 para máxima seguridad y flexibilidad.",
            "consultation_info_2_title": "El valor - la estructura gana",
            "consultation_info_2_text": "Una asignación clara en metales preciosos crea estabilidad en inflación, reformas monetarias y crisis.",
            "settings_title": "Ajustes",
            "settings_section_general": "General",
            "settings_currency_label": "Moneda de visualización",
            "settings_currency_hint": "Controla en qué moneda se muestran los precios de metales preciosos en toda la interfaz.",
            "settings_watchlist_section": "Lista de vigilancia de crisis",
            "settings_watchlist_geopolitical": "Geopolítica",
            "settings_watchlist_financial": "Ciclo económico",
            "settings_thresholds_section": "Umbrales de crisis",
            "settings_thresholds_label": "Sensibilidad",
            "settings_thresholds_standard": "Estándar",
            "settings_thresholds_sensitive": "Sensible",
            "settings_thresholds_conservative": "Conservador",
            "settings_thresholds_hint": "Influye en cuándo los eventos se marcan como alto riesgo.",
            "settings_notifications_section": "Notificaciones",
            "settings_notifications_label": "Notificaciones",
            "settings_privacy_section": "Asesoría y privacidad",
            "settings_privacy_policy": "Política de privacidad",
            "settings_privacy_note": "Los datos personales solo salen de su dispositivo cuando envía una solicitud. No se almacenan datos localmente.",
            "settings_transparency_note": "Todos los datos económicos provienen de APIs abiertas de GoldPrice.org y el Banco Mundial.",
            "settings_contact_note": "Use la pestaña Asesoría para preguntas individuales. Las respuestas cumplen el RGPD por correo electrónico.",
            "settings_done": "Listo",
            "notifications_status_active": "Activo",
            "notifications_status_denied": "Desactivado",
            "notifications_status_limited": "Limitado",
            "notifications_status_unknown": "Desconocido",
            "notifications_description_active": "Recibirá alertas cuando cambien los pronósticos o haya crisis importantes.",
            "notifications_description_denied": "Las notificaciones están desactivadas. Actívelas en los ajustes del sistema.",
            "notifications_description_limited": "Permiso temporal - confírmelo para mantener alertas críticas.",
            "notifications_description_undetermined": "Aún no se solicitó permiso.",
            "notifications_action_open_settings": "Abrir ajustes del sistema",
            "notifications_action_enable": "Activar notificaciones",
            "notifications_action_adjust": "Confirmar permiso",
            "notification_onboarding_title": "Notificaciones",
            "notification_onboarding_headline": "Alertas de crisis",
            "notification_onboarding_body": "Reciba alertas push únicas para eventos de alto riesgo. Solo enviamos avisos cuando la situación es grave.",
            "notification_onboarding_toggle_title": "Notificaciones en tiempo real",
            "notification_onboarding_toggle_hint": "Solo crisis con severidad 5+ y sin anuncios.",
            "notification_onboarding_device_hint": "Puede cambiar su decisión en cualquier momento en los ajustes del sistema.",
            "notification_onboarding_privacy_hint": "Ningún dato sale de su dispositivo. Base: App Store Guideline 5.1.1.",
            "notification_onboarding_enable": "Activar alertas de crisis",
            "notification_onboarding_later": "Quizás más tarde",
            "notification_onboarding_error_toggle": "Active el interruptor para permitir notificaciones.",
            "notification_onboarding_error_settings": "Permita notificaciones en los ajustes del sistema.",
            "notification_banner_denied": "Alertas de crisis desactivadas",
            "notification_banner_limited": "Alertas de crisis en modo silencioso",
            "notification_banner_missing": "Alertas de crisis aún no activadas",
            "notification_banner_message_denied": "Active las notificaciones para ver crisis urgentes de inmediato.",
            "notification_banner_message_limited": "Las notificaciones de la app se entregan en silencio. Active banners/sonidos.",
            "notification_banner_message_missing": "Toque aquí para activar alertas push para situaciones de alto riesgo.",
            "notification_banner_action_settings": "Abrir ajustes",
            "notification_banner_action_adjust": "Ajustar configuración",
            "privacy_policy_title": "Política de privacidad",
            "privacy_policy_website": "Sitio web",
            "privacy_policy_intro": "Procesamos sus datos solo en el dispositivo o al enviar su solicitud. No hay rastreadores ocultos ni perfiles en la nube.",
            "privacy_section_controller_title": "Responsable",
            "privacy_section_controller_body": "VermögensKompass (Vibecode GmbH) procesa solo los datos que usted comparte activamente.",
            "privacy_section_collection_title": "Resumen de la recopilación de datos",
            "privacy_section_collection_body": "• Los datos de mercado y crisis provienen de APIs públicas (World Bank, USGS, NOAA, GoldPrice.org) y se evalúan localmente.\n• No almacenamos datos personales en nuestros servidores.",
            "privacy_section_contact_title": "Contacto",
            "privacy_section_contact_body": "Cuando toca «Solicitar asesoría», enviamos su mensaje a nuestro equipo de asesoría. El envío se realiza mediante conexión segura; no almacenamos una copia.",
            "privacy_section_notifications_title": "Notificaciones",
            "privacy_section_notifications_body": "Las notificaciones de crisis se procesan solo en su dispositivo. Puede revocar el permiso en cualquier momento en los ajustes del sistema.",
            "privacy_section_tracking_title": "Analítica y seguimiento",
            "privacy_section_tracking_body": "Sin seguimiento, sin SDKs de terceros. La app funciona totalmente sin conexión con los últimos datos sincronizados.",
            "privacy_section_rights_title": "Sus derechos",
            "privacy_section_rights_body": "Puede solicitar acceso, corrección o eliminación de su contacto escribiéndonos a datenschutz@vermoegenskompass.de.",
            "offline_banner_title": "Datos sin conexión",
            "offline_banner_no_sync": "Aún no hay sincronización exitosa",
            "crisis_notification_channel": "Alertas de crisis",
            "crisis_notification_title": "Situación de crisis: %1$@",
            "crisis_notification_body": "Región: %1$@. Categoría: %2$@.",
            "generic_ok": "OK",
            "error_loading": "Error al cargar",
            "sync_error_background_update": "Error en la actualización en segundo plano",
            "async_loading": "Actualizando datos.",
            "async_retry": "Intentar de nuevo",
            "sync_last_successful": "Última sincronización: %1$@",
            "sync_never_successful": "Aún no hay sincronización exitosa",
            "consultation_submit_loading": "Enviando…",
            "not_available_short": "N/D",
            "comparison_performance_format": "Histórico %1$@ / Pronóstico %2$@",
            "comparison_chart_today": "Hoy",
            "comparison_chart_x_label": "Año",
            "comparison_chart_y_label": "Valor en %1$@",
            "macro_delta_no_trend": "Sin tendencia",
            "macro_delta_vs_previous": "%1$@%2$@%3$@ vs. año anterior",
            "macro_region_de": "DE",
            "macro_region_us": "US",
            "macro_region_uk": "UK",
            "macro_region_es": "ES",
            "currency_eur": "Euro (€)",
            "currency_usd": "Dólar estadounidense ($)",
            "settings_language_section": "Idioma",
            "settings_language_label": "Idioma de la app",
            "settings_language_hint": "Cambia el idioma de la interfaz.",
            "language_de": "Alemán",
            "language_en": "Inglés",
            "language_fr": "Francés",
            "language_es": "Español",
            "metal_insight_24h": "24h",
            "metal_insight_change": "Variación",
            "metal_source_label": "Fuente: %1$@",
            "metals_scenario_inflation_detail": "%1$@ reacciona históricamente de forma positiva al aumento de los precios al consumidor.",
            "asset_group_equities": "Mercados de acciones",
            "asset_group_real_estate": "Precios inmobiliarios",
            "asset_group_metals": "Metales preciosos",
            "asset_equity_de": "Acciones Alemania",
            "asset_equity_usa": "Acciones EE. UU.",
            "asset_equity_lon": "Acciones Londres",
            "asset_real_estate_de": "Inmobiliario Alemania",
            "asset_real_estate_es": "Inmobiliario España",
            "asset_real_estate_fr": "Inmobiliario Francia",
            "asset_real_estate_lon": "Inmobiliario Londres",
            "asset_gold": "Oro",
            "asset_silver": "Plata",
            "macro_indicator_inflation_title": "Inflación",
            "macro_indicator_inflation_description": "Inflación anual de precios al consumidor (Banco Mundial)",
            "macro_indicator_inflation_unit": "%",
            "macro_indicator_growth_title": "Crecimiento",
            "macro_indicator_growth_description": "Crecimiento real del PIB",
            "macro_indicator_growth_unit": "%",
            "macro_indicator_defense_title": "Defensa",
            "macro_indicator_defense_description": "Gasto militar como porcentaje del PIB",
            "macro_indicator_defense_unit": "% PIB",
            "benner_phase_panic_title": "Año de pánico",
            "benner_phase_panic_subtitle": "Presión de venta extrema - Fase A",
            "benner_phase_panic_guidance": "Históricamente, estos años fueron seguidos por fuertes caídas del mercado. Asegure liquidez y limite el riesgo.",
            "benner_phase_good_title": "Buenos tiempos",
            "benner_phase_good_subtitle": "Precios altos - Fase B (preferir ventas)",
            "benner_phase_good_guidance": "Valoraciones superiores a la media. Asegure ganancias y reduzca la exposición.",
            "benner_phase_hard_title": "Tiempos difíciles",
            "benner_phase_hard_subtitle": "Precios bajos - Fase C (acumulación)",
            "benner_phase_hard_guidance": "Los precios se consideran atractivos. Se recomiendan posiciones y planes de ahorro.",
            "benner_entry_summary": "%1$d - %2$@",
            "watchlist_country_ukraine": "Ucrania",
            "watchlist_country_israel": "Israel",
            "watchlist_country_taiwan": "Taiwán",
            "watchlist_country_south_africa": "Sudáfrica",
            "watchlist_country_germany": "Alemania",
            "watchlist_country_usa": "Estados Unidos",
            "watchlist_country_uk": "Reino Unido",
            "watchlist_country_japan": "Japón",
            "watchlist_country_china": "China",
            "crisis_summary_headline_none": "No se detectan eventos de alto riesgo",
            "crisis_summary_highlight_category": "%1$dx categoría %2$@",
            "crisis_summary_highlight_latest": "Último: %1$@ a las %2$@",
            "crisis_event_title_governance": "Inestabilidad política en %1$@",
            "crisis_event_title_recession": "Recesión en %1$@",
            "crisis_summary_headline_count_one": "%d evento de alto riesgo activo",
            "crisis_summary_headline_count_other": "%d eventos de alto riesgo activos",
            "crisis_summary_highlight_region_one": "%1$dx evento en %2$@",
            "crisis_summary_highlight_region_other": "%1$dx eventos en %2$@"
        ]
    ]
}
